
const { onlypageId, pageWithItemId, pageWithPageName, allIdsWithPage,  events_findAllEvent,  events_43f5e0ab858847299227083d96a6a151, events_80ae252f052e4053820240de9ecaa200, events_c7cd950c953b4337990ff374d90a201b, events_8f4363f626dd41df8f08fd0a7379371b, events_f5f5930288a64c8fa58168099af17486, events_5d3bbb35e62f424683d7a09e20f308b1, events_691728c3203f4c5c82037167600dddd3, events_9de771d4dced4912ab26f87b1adfd521, events_7ea00ef7fc8041bb89d981bfe19142b6, events_b830cd3e1f37472c989fd3eefcb51b5f, events_ac7a0837a1614235bc04aa78dc455b16, events_7e39b73dab2f445d9cf0fd92ecf391b5, events_a8420bf65cf940b2b17c6167790b56c7, events_84fbb6a10d874817b7587868c05b8d3b, events_ed2171f7c28146609c036bbddbf13ba3, events_433732d1248d4d3da901470645472fcd, events_a97aa179e34c4c9c9f111ead55d885d0, events_2940f3255b5a43ac9f95bfcc95b69d4f, } = require('./app.controller');
const _ = require('./../middleware/bypassdb.middleware')
const routes = ({ db, app }) => {
    const _db = { db, app }
    
      app.get('/', _(_db), onlypageId)
app.get('/404', _(_db), onlypageId)
app.get('/forgot-password', _(_db), onlypageId)
        app.get('/forgot-password/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password', _(_db), pageWithPageName)
        app.get('/Forgot Password/forgot-password/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/forgot-password/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Forgot Password/forgot-password/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/signup', _(_db), onlypageId)
        app.get('/signup/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup', _(_db), pageWithPageName)
        app.get('/Signup/Register/signup/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/signup/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Signup/Register/signup/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/reset-password', _(_db), onlypageId)
        app.get('/reset-password/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password', _(_db), pageWithPageName)
        app.get('/Reset Password/reset-password/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reset-password/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Reset Password/reset-password/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/change-password', _(_db), onlypageId)
        app.get('/change-password/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password', _(_db), pageWithPageName)
        app.get('/Change Password/change-password/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/change-password/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Change Password/change-password/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/login', _(_db), onlypageId)
        app.get('/login/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login', _(_db), pageWithPageName)
        app.get('/Login/login/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/login/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Login/login/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/transactions', _(_db), onlypageId)
        app.get('/transactions/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions', _(_db), pageWithPageName)
        app.get('/Transactions/transactions/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/transactions/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Transactions/transactions/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/reports', _(_db), onlypageId)
        app.get('/reports/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports', _(_db), pageWithPageName)
        app.get('/Reports/reports/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/reports/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Reports/reports/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/settings', _(_db), onlypageId)
        app.get('/settings/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings', _(_db), pageWithPageName)
        app.get('/Settings/settings/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/settings/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Settings/settings/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/dashboard', _(_db), onlypageId)
        app.get('/dashboard/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard', _(_db), pageWithPageName)
        app.get('/Dashboard/dashboard/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/dashboard/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Dashboard/dashboard/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/payment-success', _(_db), onlypageId)
        app.get('/payment-success/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success', _(_db), pageWithPageName)
        app.get('/Payment Success/payment-success/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-success/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Success/payment-success/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/payment-cancel', _(_db), onlypageId)
        app.get('/payment-cancel/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel', _(_db), pageWithPageName)
        app.get('/Payment Cancel/payment-cancel/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/payment-cancel/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Payment Cancel/payment-cancel/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/summary', _(_db), onlypageId)
        app.get('/summary/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary', _(_db), pageWithPageName)
        app.get('/Summary/summary/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/summary/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Summary/summary/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/invoices', _(_db), onlypageId)
        app.get('/invoices/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices', _(_db), pageWithPageName)
        app.get('/Invoices/invoices/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/invoices/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Invoices/invoices/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/cards', _(_db), onlypageId)
        app.get('/cards/assets_and_liabilities/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards', _(_db), pageWithPageName)
        app.get('/Cards/cards/assets_and_liabilities/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/borrowers/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/borrowers/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/comment/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/comment/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/loan_applications/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/loan_applications/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/news_update/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/news_update/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/plaid_setting/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/plaid_setting/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/redeem_miles/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/redeem_miles/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/role/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/role/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/stripe_connected_accounts/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/stripe_connected_accounts/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/task_status/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/task_status/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/team/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/team/:itemId?', _(_db), allIdsWithPage) 
        app.get('/cards/user/:itemId?', _(_db), pageWithItemId)
        app.get('/Cards/cards/user/:itemId?', _(_db), allIdsWithPage) 
app.get('/api/v1/events', _(_db), events_findAllEvent)
app.get('/api/v1/events/43f5e0ab-8588-4729-9227-083d96a6a151', _(_db), events_43f5e0ab858847299227083d96a6a151)
app.get('/api/v1/events/80ae252f-052e-4053-8202-40de9ecaa200', _(_db), events_80ae252f052e4053820240de9ecaa200)
app.get('/api/v1/events/c7cd950c-953b-4337-990f-f374d90a201b', _(_db), events_c7cd950c953b4337990ff374d90a201b)
app.get('/api/v1/events/8f4363f6-26dd-41df-8f08-fd0a7379371b', _(_db), events_8f4363f626dd41df8f08fd0a7379371b)
app.get('/api/v1/events/f5f59302-88a6-4c8f-a581-68099af17486', _(_db), events_f5f5930288a64c8fa58168099af17486)
app.get('/api/v1/events/5d3bbb35-e62f-4246-83d7-a09e20f308b1', _(_db), events_5d3bbb35e62f424683d7a09e20f308b1)
app.get('/api/v1/events/691728c3-203f-4c5c-8203-7167600dddd3', _(_db), events_691728c3203f4c5c82037167600dddd3)
app.get('/api/v1/events/9de771d4-dced-4912-ab26-f87b1adfd521', _(_db), events_9de771d4dced4912ab26f87b1adfd521)
app.get('/api/v1/events/7ea00ef7-fc80-41bb-89d9-81bfe19142b6', _(_db), events_7ea00ef7fc8041bb89d981bfe19142b6)
app.get('/api/v1/events/b830cd3e-1f37-472c-989f-d3eefcb51b5f', _(_db), events_b830cd3e1f37472c989fd3eefcb51b5f)
app.get('/api/v1/events/ac7a0837-a161-4235-bc04-aa78dc455b16', _(_db), events_ac7a0837a1614235bc04aa78dc455b16)
app.get('/api/v1/events/7e39b73d-ab2f-445d-9cf0-fd92ecf391b5', _(_db), events_7e39b73dab2f445d9cf0fd92ecf391b5)
app.get('/api/v1/events/a8420bf6-5cf9-40b2-b17c-6167790b56c7', _(_db), events_a8420bf65cf940b2b17c6167790b56c7)
app.get('/api/v1/events/84fbb6a1-0d87-4817-b758-7868c05b8d3b', _(_db), events_84fbb6a10d874817b7587868c05b8d3b)
app.get('/api/v1/events/ed2171f7-c281-4660-9c03-6bbddbf13ba3', _(_db), events_ed2171f7c28146609c036bbddbf13ba3)
app.get('/api/v1/events/433732d1-248d-4d3d-a901-470645472fcd', _(_db), events_433732d1248d4d3da901470645472fcd)
app.get('/api/v1/events/a97aa179-e34c-4c9c-9f11-1ead55d885d0', _(_db), events_a97aa179e34c4c9c9f111ead55d885d0)
app.get('/api/v1/events/2940f325-5b5a-43ac-9f95-bfcc95b69d4f', _(_db), events_2940f3255b5a43ac9f95bfcc95b69d4f)

}
module.exports = routes