name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '8.11.3'

    - name: Install Dependencies
      run: |
        sudo apt install nodejs
        sudo apt install npm
        npm install npm -g
        cd bizzy3932/project/
        npm install

    - name: Setup Database
      run: |
        cd bizzy3932/dump/project_747fy36r61t3002j531x9ki1zj15
        mongorestore --db project_747fy36r61t3002j531x9ki1zj15 --verbose project_747fy36r61t3002j531x9ki1zj15/

    - name: Run Project
      run: |
        cd bizzy3932/project/
        node index.js

    # Add any additional steps such as testing or deployment here
