name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debugging - Print Working Directory
      run: pwd

    - name: Debugging - List Directory Contents
      run: ls -la

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        sudo apt install nodejs
        sudo apt install npm
        npm install npm -g
        cd bizzy3932/project/ # Check if this path is correct
        npm install

    - name: Setup Database Schema and Run Migrations
      run: |
        cd bizzy3932/project/
        # Adjust this line to match your project's migration command or remove if not needed
        npm run migrate 

    - name: Run Project
      run: |
        cd bizzy3932/project/
        node index.js
